#! /bin/bash

sync_dir() {
  # Trailing slashes on the name would double up in the paths below.
  local name="${2%/}"
  local target_dir="$1/$name"
  local sync_dir="$git_dir/$name"

  echo "Syncing dir $target_dir -> $sync_dir"

  if ! [ -d "$target_dir" ]; then
    echo "[!] Target dir doesn't exist ($target_dir)"
    return
  fi

  # Always copy onto a missing destination. Creating it first would make cp
  # nest the source inside it instead (dot-files/hypr/hypr/), which is what
  # used to happen the first time a directory was ever synced.
  rm -rf "$sync_dir"
  mkdir -p "$(dirname "$sync_dir")"
  cp -r "$target_dir" "$sync_dir"
}

sync_file() {
  local target_file_path="$1"
  local sync_dir="$git_dir/${2%/}"
  local sync_file_name="$3"

  echo "Syncing file $target_file_path -> $sync_dir/$sync_file_name"

  if ! [ -f "$target_file_path" ]; then
    echo "[!] Target file doesn't exist ($target_file_path)"
    return
  fi

  mkdir -p "$sync_dir"
  cp "$target_file_path" "$sync_dir/$sync_file_name"
}

# Omarchy plugins come in two flavours and only one of them is worth copying.
# A plugin installed with `omarchy plugin add` is a git checkout of somebody
# else's repo: the command that brings it back is the whole story, and copying
# the tree would just vendor a second copy of an upstream project. A plugin
# built by hand has no upstream at all, so this repo is the only place it
# exists and the project itself has to be kept.
#
# Whether a plugin is enabled, and where it sits on the bar, lives in
# omarchy/shell.json. The generated installer puts that file back too, last,
# so a restore is one command instead of two steps in the right order.
sync_omarchy_plugins() {
  local plugins_dir="$config_dir/omarchy/plugins"
  local sync_dir="$git_dir/omarchy/plugins"
  local install_script="$sync_dir/install.sh"

  echo "Syncing omarchy plugins $plugins_dir -> $sync_dir"

  # Rebuilt from scratch every run, so a plugin removed from the machine also
  # disappears from here instead of lingering as a stale copy.
  rm -rf "$sync_dir"

  if ! [ -d "$plugins_dir" ]; then
    echo "[!] Target dir doesn't exist ($plugins_dir)"
    return
  fi

  mkdir -p "$sync_dir"

  cat > "$install_script" <<'HEADER'
#! /bin/bash

# Generated by sync.sh -- do not edit by hand.
#
# Restores the omarchy plugins on a fresh machine. Plugins with an upstream
# are re-added from it; plugins without one are copied out of this repo.
# The bar layout (omarchy/shell.json) is restored at the end.

set -euo pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
plugins_dir="$HOME/.config/omarchy/plugins"

mkdir -p "$plugins_dir"

HEADER

  local path id origin
  for path in "$plugins_dir"/*/; do
    [ -d "$path" ] || continue
    id="$(basename "$path")"
    origin="$(git -C "$path" remote get-url origin 2>/dev/null || true)"

    if [ -n "$origin" ]; then
      echo "  $id -> install command only ($origin)"
      cat >> "$install_script" <<EOF
# $id
if [ -d "\$plugins_dir/$id" ]; then
  omarchy plugin update $id --yes
else
  omarchy plugin add $origin --yes
fi

EOF
      continue
    fi

    echo "  $id -> no upstream, copying the project"
    cp -r "${path%/}" "$sync_dir/$id"
    rm -rf "$sync_dir/$id/.git"
    cat >> "$install_script" <<EOF
# $id (built here, restored from this repo)
rm -rf "\$plugins_dir/$id"
cp -r "\$here/$id" "\$plugins_dir/$id"

EOF
  done

  cat >> "$install_script" <<'FOOTER'
# The bar layout names these plugins, so it is only safe to drop in once they
# are all on disk. Hence last.
shell_json="$here/../shell.json"
target="$HOME/.config/omarchy/shell.json"

if ! [ -f "$shell_json" ]; then
  echo "[!] No shell.json in this checkout; bar layout left alone"
  exit 0
fi

if [ -f "$target" ] && ! cmp -s "$shell_json" "$target"; then
  backup="$target.bak-$(date +%Y%m%d%H%M%S)"
  cp "$target" "$backup"
  echo "Kept the previous bar layout at $backup"
fi

mkdir -p "$(dirname "$target")"
cp "$shell_json" "$target"
echo "Restored $target"

# A running shell keeps the old layout in memory until it is restarted.
if command -v omarchy >/dev/null 2>&1 && pgrep -x quickshell >/dev/null 2>&1; then
  omarchy restart shell || echo "[!] Could not restart the shell; run: omarchy restart shell"
else
  echo "Start the shell to pick it up (omarchy restart shell)."
fi
FOOTER

  chmod +x "$install_script"
}

config_dir="$HOME/.config"
local_dir="$HOME/.local/share"
git_dir="$HOME/dot-files"

echo "Syncronization started"
echo ""

echo "Syncing folders"

sync_dir "$config_dir" "ghostty/"
sync_dir "$config_dir" "hypr/"
sync_dir "$config_dir" "nvim/"

echo ""
echo "Syncing files"

sync_file "$HOME/.bashrc" "bash/" ".bashrc"
sync_file "$HOME/intel-undervolt/intel-undervolt.conf" "intel-undervolt" "intel-undervolt.conf"
sync_file "$config_dir/tmux/tmux.conf" "tmux" "tmux.conf"
sync_file "$config_dir/omarchy/extensions/omarchy-menu.jsonc" "omarchy/extensions" "omarchy-menu.jsonc"
sync_file "$config_dir/omarchy/shell.json" "omarchy" "shell.json"
sync_file "$config_dir/uwsm/env-hyprland" "uwsm" "env-hyprland"
# Holds the default browser/editor picked via `omarchy default ...`.
sync_file "$config_dir/mimeapps.list" "xdg" "mimeapps.list"

echo ""
echo "Syncing omarchy plugins"

sync_omarchy_plugins

echo ""
echo "Pushing to github"

cd "$git_dir" || exit 1
git add -A

if git diff --cached --quiet; then
  echo "Nothing changed, skipping commit"
else
  git commit -q -m "sync: $(date -u)"
  git push -q
fi

echo "Syncronization done"
