################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=AOC 24G2W1G4 ATNM4XA001012,1920x1080@144,auto-left,1,vrr,1
monitor=AU Optronics 0x21ED,1920x1080@60,auto,1.2
monitor=,highres@60,auto-left,1
