# Extra autostart processes
# exec-once = uwsm-app -- my-service

exec-once = [workspace 1 silent] omarchy-launch-browser
exec-once = [workspace 2 silent] uwsm-app -- xdg-terminal-exec
exec-once = [workspace 3 silent] uwsm-app -- obsidian
exec-once = [workspace 5 silent] uwsm-app -- discord
# exec-once = [workspace special:scratchpad silent] omarchy-launch spotify
exec-once = [workspace special:scratchpad silent] omarchy-launch-tui ncspot

exec-once = easyeffects --gapplication-service

windowrule {
  name = open-discord-on-workspace-5
  match:class = ^(discord)$
  workspace = 5 silent
}

windowrule {
  name = open-spotify-on-scratchpad
  match:class = ^(spotify)$
  workspace = special:scratchpad silent
}
