# Extra autostart processes
# exec-once = uwsm app -- my-service
#

windowrule = workspace 3 silent, title:^(Discord)$

exec-once = kanshi

exec-once = [workspace 1 silent] $browser
exec-once = [workspace 2 silent] $terminal
exec-once = [workspace 3 silent] omarchy-launch-or-focus discord
exec-once = [workspace special:scratchpad silent] omarchy-launch-or-focus spotify

