# Extra autostart processes
# exec-once = uwsm app -- my-service


exec-once = [workspace 1 silent] $browser
exec-once = [workspace 2 silent] $terminal
exec-once = [workspace 4 silent] omarchy-launch-or-focus obsidian
exec-once = [workspace 5 silent] omarchy-launch-or-focus discord
exec-once = [workspace special:scratchpad silent] omarchy-launch-or-focus spotatui

windowrule {
  name = open-discord-on-workspace-6
  match:title = ^(Discord)$
  workspace = 5 silent
}

windowrule {
  name = open-spotigy-on-special-workspace
  match:class = spotify
  workspace = special:scratchpad silent
}

