# Extra env variables
# env = AQ_DRM_DEVICES,/dev/dri/card0:/dev/dri/card1

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

misc {
  vrr = 1
}

cursor { 
  no_hardware_cursors = true
} 

debug {
  overlay = false
}

# general {
#   allow_tearing = true
# }
