# Extra env variables

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

misc {
  vrr = 1
}

cursor { 
  no_hardware_cursors = true
} 

debug {
  overlay = false
  disable_logs = false
}
