# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 0

    # inactive_opacity = 0.7
 
    # Make the incative window darker [0.0 - 1.0]
    dim_inactive = true
    dim_strength = 0.3

    shadow {
        enabled = false
    }
    blur {
        enabled = false
    }
}

windowrule = opacity 1 1, match:tag default-opacity
