#! /bin/bash

# Generated by sync.sh -- do not edit by hand.
#
# Restores the omarchy plugins on a fresh machine. Plugins with an upstream
# are re-added from it; plugins without one are copied out of this repo.
# The bar layout (omarchy/shell.json) is restored at the end.

set -euo pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
plugins_dir="$HOME/.config/omarchy/plugins"

mkdir -p "$plugins_dir"

# quickshell.spotify
if [ -d "$plugins_dir/quickshell.spotify" ]; then
  omarchy plugin update quickshell.spotify --yes
else
  omarchy plugin add https://github.com/stappmus/Omarchy-Spotify.git --yes
fi

# xandfcosta.hw-monitor (built here, restored from this repo)
rm -rf "$plugins_dir/xandfcosta.hw-monitor"
cp -r "$here/xandfcosta.hw-monitor" "$plugins_dir/xandfcosta.hw-monitor"

# The bar layout names these plugins, so it is only safe to drop in once they
# are all on disk. Hence last.
shell_json="$here/../shell.json"
target="$HOME/.config/omarchy/shell.json"

if ! [ -f "$shell_json" ]; then
  echo "[!] No shell.json in this checkout; bar layout left alone"
  exit 0
fi

if [ -f "$target" ] && ! cmp -s "$shell_json" "$target"; then
  backup="$target.bak-$(date +%Y%m%d%H%M%S)"
  cp "$target" "$backup"
  echo "Kept the previous bar layout at $backup"
fi

mkdir -p "$(dirname "$target")"
cp "$shell_json" "$target"
echo "Restored $target"

# A running shell keeps the old layout in memory until it is restarted.
if command -v omarchy >/dev/null 2>&1 && pgrep -x quickshell >/dev/null 2>&1; then
  omarchy restart shell || echo "[!] Could not restart the shell; run: omarchy restart shell"
else
  echo "Start the shell to pick it up (omarchy restart shell)."
fi
