#! /bin/bash

# Generated by sync.sh -- do not edit by hand.
#
# Restores the omarchy plugins on a fresh machine. Plugins with an upstream
# are re-added from it; plugins without one are copied out of this repo.
# Enablement and bar placement come from omarchy/shell.json.

set -euo pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
plugins_dir="$HOME/.config/omarchy/plugins"

mkdir -p "$plugins_dir"

# quickshell.spotify
if [ -d "$plugins_dir/quickshell.spotify" ]; then
  omarchy plugin update quickshell.spotify --yes
else
  omarchy plugin add https://github.com/stappmus/Omarchy-Spotify.git --yes
fi

# xandfcosta.hw-monitor (built here, restored from this repo)
rm -rf "$plugins_dir/xandfcosta.hw-monitor"
cp -r "$here/xandfcosta.hw-monitor" "$plugins_dir/xandfcosta.hw-monitor"

