# ============================================================================
# Omarchy Tmux Theme: miasma
# ============================================================================
# 
# PERSISTENT THEME PROFILE
# This file is yours to customize! Your changes will persist across theme
# switches - when you return to this theme, your customizations remain.
#
# ============================================================================

set -g @plugin 'niksingh710/minimal-tmux-status'

set -g @minimal-tmux-bg "#78824b"
set -g @minimal-tmux-fg "#c2c2b0"
set -g @minimal-tmux-status "bottom"
set -g @minimal-tmux-justify "centre"
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""

# ============================================================================
